services:
  api:
    build:
      context: .
      dockerfile: diary-api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - /c/upload:/upload
    networks:
      - diary-net

  front:
    build:
      context: .
      dockerfile: diary-front/Dockerfile
    ports:
      - "3000:80"
    networks:
      - diary-net

  db:
    container_name: diary-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: diary
      POSTGRES_USER: ho980719
      POSTGRES_PASSWORD: rlawnsgh12!
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - diary-net

  redis:
    container_name: diary-redis
    image: redis:7.0-alpine
    command: ["redis-server", "--requirepass", "rlawnsgh12!"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  pgdata:
  redis-data:

networks:
  diary-net:
    external: true