services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    restart: always
    container_name: diary-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - diary-net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.2
    restart: always
    environment:
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
    container_name: diary-logstash
    volumes:
      - ./logstash/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    networks:
      - diary-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.2
    restart: always
    container_name: diary-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - diary-net

networks:
  diary-net:      
    external: true
    name: diary_diary-net  # Docker 네트워크 이름
