spring:
  application:
    name: diary-api
  config:
    import:
      - classpath:application-auth.yaml
      - classpath:application-core.yaml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/diary
    username: ho980719
    password: rlawnsgh12!

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: INFO
    com.ho.diary: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
